steps:
#  – build your container, e.g. with Dockerfile
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/product-sync:$SHORT_SHA', '.' ]
#  – push it up to Artifact Registry (or Container Registry)
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/product-sync:$SHORT_SHA' ]
#  – deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - product-sync
    - --image
    - gcr.io/$PROJECT_ID/product-sync:$SHORT_SHA
    - --region
    - us-central1
    - --platform
    - managed
