steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - -t
    - "gcr.io/$PROJECT_ID/product-sync:$BUILD_ID"
    - .
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - "gcr.io/$PROJECT_ID/product-sync:$BUILD_ID"
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - product-sync
    - --image=gcr.io/$PROJECT_ID/product-sync:$BUILD_ID
    - --region=us-central1
    - --platform=managed
