steps:
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -t
    - gcr.io/$PROJECT_ID/product-sync:${SHORT_SHA}
    - .
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - gcr.io/$PROJECT_ID/product-sync:${SHORT_SHA}
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    - run
    - jobs
    - execute
    - product-sync-job
    - --image=gcr.io/$PROJECT_ID/product-sync:${SHORT_SHA}
    - --region=us-central1
